modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://gitlab.com/stalking-dragons/minecraft/utility-nexus-admin"
logoFile="icon.png"
credits="Developed by Stalking Dragons"
description='''Utility Nexus Admin - A utility mod for server administration with datapack loading functionality and other admin tools.'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"